---
- name: Enviando e-mail com ansible
  hosts: localhost
  tasks:
  - sendgrid:
    api_key: SG...
    from_address: "barrosoti@gmail.com"
    to_addresses:
      - "barrosoes@gmail.com"
    subject: "Deployment success."
    body: "The most recent Ansible deployment was successful."
